spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.0.3:9094
      group-id: coupling-test
    producer:
      bootstrap-servers: 192.168.0.3:9094
    topics: outbox.event.test-topic, general-topic

  r2dbc:
    url: r2dbc:mysql://192.168.0.3/coupling
    username: mysqluser
    password: mysqlpw
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
server:
  port: 8080